version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven
      - apt-get update && apt-get install -y maven
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build completed Succesfully
