version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven
      - apt-get update && apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - echo Build completed on `date`
